# Generated by Django 3.0.4 on 2020-03-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('QT', 'Quarantined'), ('SP', 'Suspected'), ('IN', 'Infected'), ('RC', 'Recovered'), ('DC', 'Deceased')], default='SP', max_length=2)),
                ('description', models.CharField(max_length=1200)),
                ('num_cases', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
