# Generated by Django 3.0.4 on 2020-03-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaCaseRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('QT', 'Quarantined'), ('SP', 'Suspected'), ('IN', 'Infected'), ('RC', 'Recovered'), ('DC', 'Deceased')], default='SP', max_length=2)),
                ('description', models.CharField(max_length=1200)),
                ('link', models.URLField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='CoronaCase',
        ),
    ]
