# Generated by Django 3.0.4 on 2020-03-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_coronacaseraw_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronacaseraw',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='coronacaseraw',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
    ]
