# Generated by Django 3.0.4 on 2020-03-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20200312_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coronacaseraw',
            name='link',
        ),
    ]
