# Generated by Django 3.0.4 on 2020-03-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_coronacaseraw_link'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coronacaseraw',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='location'),
        ),
    ]
